version: '3.8'
services:
  backend:
    container_name: api_backend
    restart: always

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: api

    links:
      - db
    networks:
      - mysql_network

    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    expose:
      - 3000
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - mysql_network

    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:

networks:
  mysql_network:
    driver: local
