version: '3.8'
services:
  backend:
    container_name: api_backend
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: api
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '3001:3001'
    depends_on:
      - db
    command: npm run dev
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: api
    ports:
      - 3301:3306
    expose:
      - 3306
    cap_add:
      - SYS_NICE
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
